server:
    port: 8888
spring:
    profiles:
        active: native
    cloud:
        config: 
            server:
                native:
                    searchLocations: file:///c:/learn/cloud/config/licensingservice
                    
