server:
    port: 8090

spring:
    application:
        name: LicenseService
    profile:
        active:
            default
    eureka:
        instance:
            preferIpAddress: true
        client:
            registerWithEureka: true
            fetchRegistry: true
            serviceUrl:
                defaultZone: http://localhost:8761/eureka/
            

        
        